---
- hosts: 172.31.21.222
  become: yes
  tasks:
  - include_tasks: file.yml
  
  - name: I want to install webserver on ubuntu node
    apt:
      name: apache2
      state: present

  - name: I want to start webserver on ubuntu node
    service:
      name: apache2
      state: started

  - name: I wnat ot copy Myindex.j2 file into node side
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
