---

- name: create directory
  file:
    path: /opt/tomcat
    state: directory
    mode: 0775

- name: extract tomcat tar file into /opt/tomcat folder
  command:
    cmd: sudo tar xzvf /home/ubuntu/apache-tomcat-8.5.5.tar.gz -C /opt/tomcat --strip-components=1
    creates: /opt/tomcat/LICENSE 